name: ptos
description: Custom Bazzite image with extra apps
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system_files
        destination: /

  # Fix /opt permissions (replaces fix-opt.sh logic)
  - type: script
    scripts:
      - add-repos.sh
      - fix-opt.sh

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.google.Chrome
          - com.spotify.Client
          - com.discordapp.Discord
          - org.videolan.VLC
          - com.heroicgameslauncher.hgl

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - lutris
        - sunshine
        - waydroid

  - type: dconf
    settings:
      org/gnome/shell:
        favorite-apps:
          - 'com.google.Chrome.desktop'
          - 'steam.desktop'
          - 'com.spotify.Client.desktop'
          - 'com.discordapp.Discord.desktop'
          - 'com.heroicgameslauncher.hgl.desktop'
          - 'org.gnome.Nautilus.desktop' # Files
          - 'ptyxis.desktop' # Bazzite's default terminal

  - type: signing
