name: ptos
description: Custom Bazzite image with extra apps
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system_files
        destination: /

  # Fix /opt permissions (replaces fix-opt.sh logic)
  # BlueBuild doesn't have a native 'fix-opt' module yet, so we might need a script
  # or rely on base image behavior. For now, let's include the script.
  - type: script
    scripts:
      - add-repos.sh
      - fix-opt.sh

  - type: rpm-ostree
    install:
      - zsh
      - google-chrome-stable
      - spotify-client
      - discord
      - vlc
      - code
      - heroic-games-launcher-bin
    remove:
      - firefox
      - firefox-langpacks
      - sunshine
      - lutris
      - waydroid

  - type: signing


